server:
  port: 8081
spring:
  security:
    user:
      name: xxx
      password: yyy
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /killme
  datasource:
    url: jdbc:h2:mem:desertwinddb
    driveClassName: org.h2.Driver
    username: mester
    password: xxx
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
