@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": false,
    "cutClient": false,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 4,
    "backwardDepth": 4,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "BothDirections" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 3,
    "showDetailedClassStructure": true
  },
  "rootClass": "DesertWind",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1606736256 { 
   	label=kodenigaz
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1252239051 { 
   	label=desertwind
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   DesertWind1965813016[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DesertWind</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- isAktualisJelenetHalal(aktualisJelenet: Jelenet): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UI1965813016[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UI</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># bekero(): String</TD></TR>
<TR><TD ALIGN="LEFT" ># megjelenito(aktualisJelenet: Jelenet)</TD></TR>
<TR><TD ALIGN="LEFT" ># parancsertelmezo(aktualisJelenet: Jelenet, parancs: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

subgraph cluster_375531433 { 
   	label=scene
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   Elso408797238[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Elso</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ parancs_Ertelmezo(parancs: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ szoveg()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Harmadik408797238[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Harmadik</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ parancs_Ertelmezo(parancs: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ szoveg()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Hatodik408797238[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Hatodik</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ parancs_Ertelmezo(parancs: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ szoveg()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Jelenet408797238[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)Jelenet</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ parancs_Ertelmezo(parancs: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ szoveg()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

Masodik408797238[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Masodik</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ parancs_Ertelmezo(parancs: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ szoveg()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Negyedik408797238[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Negyedik</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ parancs_Ertelmezo(parancs: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ szoveg()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Otodik408797238[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Otodik</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ parancs_Ertelmezo(parancs: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ szoveg()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Verzio408797238[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Verzio</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   verzio: VerzioErtek [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 
} 

'edges    
Elso408797238 -> Jelenet408797238[arrowhead=empty, arrowtail=none, dir=both];
Harmadik408797238 -> Jelenet408797238[arrowhead=empty, arrowtail=none, dir=both];
Hatodik408797238 -> Jelenet408797238[arrowhead=empty, arrowtail=none, dir=both];
Masodik408797238 -> Jelenet408797238[arrowhead=empty, arrowtail=none, dir=both];
Negyedik408797238 -> Jelenet408797238[arrowhead=empty, arrowtail=none, dir=both];
Otodik408797238 -> Jelenet408797238[arrowhead=empty, arrowtail=none, dir=both];

Verzio408797238 -> Elso408797238[arrowhead=none, arrowtail=empty, dir=both];
Verzio408797238 -> Harmadik408797238[arrowhead=none, arrowtail=empty, dir=both];
Verzio408797238 -> Hatodik408797238[arrowhead=none, arrowtail=empty, dir=both];
Verzio408797238 -> Masodik408797238[arrowhead=none, arrowtail=empty, dir=both];
Verzio408797238 -> Negyedik408797238[arrowhead=none, arrowtail=empty, dir=both];
Verzio408797238 -> Otodik408797238[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml
